language: elixir

cache:
  directories:
  - deps

elixir:
  - 1.9.1

otp_release:
  - 22.0

services:
  - postgresql

sudo: required
dist: trusty

addons:
  postgresql: "9.6"

script:
  - mix test.all
